### ISSUE TITLE
Missing Migrations

### ISSUE THREAD

**Issue by dbd5** [hauntd/yii2-vote#1]
Hi,

I'm trying to check out your model but I can't seem to figure out the configuration from the documentation. 

The configuration (below) has comments where to use "your model" so I imagine there should be migration code for tables corresponding to **itemVote, itemVoteGuests, itemLike** and **itemFavourite** but there is none. Please clarify what I am missing.

Thanks

```
'modules' => [
'vote' => [
  'class' => hauntd\vote\Module::class,
    'guestTimeLimit' => 3600,
    'entities' => [
      // Entity -> Settings
      'itemVote' => app\models\Item::class, // your model
      'itemVoteGuests' => [
          'modelName' => app\models\Item::class, // your model
          'allowGuests' => true,
      ],
      'itemLike' => [
          'modelName' => app\models\Item::class, // your model
          'type' => hauntd\vote\Module::TYPE_TOGGLE, // like/favorite button
      ],
      'itemFavorite' => [
          'modelName' => app\models\Item::class, // your model
          'type' => hauntd\vote\Module::TYPE_TOGGLE, // like/favorite button
      ],
  ],
],
```

  ],

**Comment by hauntd** [comment]
Hi @dbd5 

All needed migrations are in `migrations` directory and you can install them by running following command: 

`php yii migrate/up --migrationPath=@vendor/hauntd/yii2-vote/migrations`

`itemVote`, `itemVoteGuests` etc. are just unique keys (aliases) to separate votes. They do not need any migrations. This allows you to use multiple vote widgets for the same model (`app\models\Item` in the example).

**Comment by dbd5** [comment]
Thanks @hauntd!

My problem is that after installation,  the Config file was showing errors wherever the reference "app\models\Item" occurs so I made changes to **point the config to the model files** in the vendor folder (see config below). I am not sure this is right because you did not say so in your docs and moreover, it is not working -- and it is not giving any errors.

Could you let me know how to setup the Config correctly or advise if the settings below are correct. 

Thanks

---

```
    'vote' => [
        'class' => hauntd\vote\Module::class,
        'guestTimeLimit' => 3600,
        'entities' => [
            // Entity -> Settings
            'itemVote' => \hauntd\vote\models\Vote::class, // your model
            'itemVoteGuests' => [
                'modelName' => \hauntd\vote\models\Vote::class, // your model
                'allowGuests' => true,
            ],
            'itemLike' => [
                'modelName' => \hauntd\vote\models\Vote::class, // your model
                'type' => hauntd\vote\Module::TYPE_TOGGLE, // like/favorite button
            ],
            'itemFavorite' => [
                'modelName' => \hauntd\vote\models\Vote::class, // your model
                'type' => hauntd\vote\Module::TYPE_TOGGLE, // like/favorite button
            ],
        ],
    ],
```

**Comment by dbd5** [comment]
I have also tried to remove the entities array from Config to see if I can make it work for the case where you don't need multiple instances in the same page. I haven't been able to get it to work

**Comment by hauntd** [comment]
What's your model class? Let's say you want to attach vote module to `common\models\Post`. In this case your config should be like this:

```
    'vote' => [
        'class' => hauntd\vote\Module::className(),
        'guestTimeLimit' => 3600,
        'entities' => [
            'postVote' => [
                'modelName' => \common\models\Post::className(),
                'allowGuests' => true,
            ],
        ],
    ],
```

You can name entities (like `postVote`) whatever you want, but don't change it on production.

**Comment by dbd5** [comment]
Ah!

Then means there will be entries in the Config array for any models I wish to add the widgets to, its all clear now. Thanks
