### ISSUE TITLE
Wrong field type `vote_aggregate`.`entity`

### ISSUE THREAD

**Issue by kirc0de** [hauntd/yii2-vote#11]
You have code:

`
public function encodeEntity($entity)
{
    return crc32($entity);
}
`

But in your migrations your field `vote_aggregate`.`entity` is UNSIGNED.

So, with my config: 
```
'modules' => [
        'vote' => [
            // ...
            'entities' => [
                // Entity -> Settings
                'postVote' => [
                    'modelName' => \common\models\Post::className(),
                    'allowGuests' => false,
                ], // your model
            ],
        ],
    ],
```

This `crc32('postVote')` returns `-301023533`, which is <0.

**Comment by kirc0de** [comment]
Also this problem with field `vote.entity`

**Comment by hauntd** [comment]
Thanks for your feedback.

Fixed. 9c3bfcc2552c94482a599fe21f42b2c9697c4976
