### ISSUE TITLE
Migration error with boolean field

### ISSUE THREAD

**Issue by kirc0de** [hauntd/yii2-vote#12]
MySQL 5.5, Win7, Openserver

Migration error:

```
execute SQL: ALTER TABLE vote ALTER COLUMN value TYPE boolean USING CASE value WHEN 0 THEN false ELSE true END ...Exception 'yii\db\Exception' 
with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds 
to your MySQL server version for the right syntax to use near 'TYPE boolean USING CASE value WHEN 0 THEN false ELSE true END' at line 1

The SQL being executed was: ALTER TABLE vote ALTER COLUMN value TYPE boolean USING CASE value WHEN 0 THEN false ELSE true END'
```

With old migration like this all is ok:
`$this->alterColumn('{{%vote}}', 'value', $this->boolean()->notNull());`

Problem with commit https://github.com/hauntd/yii2-vote/pull/9/commits/07f2d6274cd943e0a0399ad91a0fcdcd67eff4a5

**Comment by kirc0de** [comment]
Can we fix it?
What problem was with these code? `$this->alterColumn('{{%vote}}', 'value', $this->boolean()->notNull());`

**Comment by takizo** [comment]
Got the same error as well @sokoji manage to fix it?

**Comment by ghost** [comment]
Got the same error. How to fix this? Or could anyone give me instructions to manually create these tables

**Comment by kirc0de** [comment]
@takizo @shrikanth003 I've just create PR, need for apply it. 

@hauntd Can u please check it and apply or comment?
