### ISSUE TITLE
Wrong vote up / down tally

### ISSUE THREAD

**Issue by dbd5** [hauntd/yii2-vote#2]
Hi,

It looks like the tally of the vote up/down button is not adding correctly.
You may be able to reproduce this by voting up, having a second person vote up from another IP address and then voting down. The tally should be +1 +1 -1 = +1 but it the widget displays 0 instead

**Comment by hauntd** [comment]
Hi @dbd5,

When you're voting up/down right after you have voted (down/up), your value is actually changed.
The default time limit for guests is 1 hour (1 vote/hour per IP for the one vote item). After this time, new votes will be added (+1 or -1) and not replaced/changed.

**Comment by dbd5** [comment]
Ok, thanks
Will review again
