### ISSUE TITLE
Error when $targetModel::primaryKey() != 'id'

### ISSUE THREAD

**Issue by andrew-artamonov** [hauntd/yii2-vote#20]
https://github.com/hauntd/yii2-vote/blob/9977766926ac2a46a1b2cb27c3227318c571140f/models/VoteForm.php#L79

need replace to 
`$entityModel = $targetModel->findOne([$targetModel::primaryKey()[0] => $this->targetId]);`

**Comment by hauntd** [comment]
Thank you, added.
