### ISSUE TITLE
Counting and Rewarding

### ISSUE THREAD

**Issue by dbd5** [hauntd/yii2-vote#3]
Hello,

I have successfully attached the widgets to blog posts.

What I will now like to do is reward the blog authors that receive the highest number of likes, or favorites. I will also like to order my posts based on the ones that receive the highest number of vote up. 

Are there any in built methods for this?
or Alternatively, how can I query the vote tables to determine the authors whose articles have been most liked or whose articles have been voted most up?

Thanks once again!

**Comment by hauntd** [comment]
Hello @dbd5, sorry for the delay.

I have updated the docs - https://github.com/hauntd/yii2-vote/blob/master/docs/behaviors.md#example, please check. 

Hope this helps.

**Comment by dbd5** [comment]
Hi @hauntd,

I'm happy to confirm that it works, thanks

Adam
