### ISSUE TITLE
Sort query by positive - negative

### ISSUE THREAD

**Issue by dbd5** [hauntd/yii2-vote#5]
Hi @hauntd ,

The new attributes and the behaviours are great, I've been able to get them to work - thanks.

Your interfaces make it easy to get negative, positive statically and with two calls we can compute positive - negative. However I've not been able to figure out how to sort a query output with the voting result (The position of each entry in the result is the result of the expression positive - negative). This will make it possible to sort lists based on up down votes of users.  

Is this possible? Or can this be achieved only by making changes to getVoteAggregate in VoteBehaviour? 

Regards,

Adam

**Comment by hauntd** [comment]
Let's say you have following module configuration:

```php
'modules' => [
    'vote' => [
        'class' => hauntd\vote\Module::class,
        'controllerMap' => [
            'default' => 'app\controllers\VoteController',
        ],
        'entities' => [
            'itemLike' => [
                'modelName' => app\models\Item::class,
                'type' => hauntd\vote\Module::TYPE_TOGGLE,
            ],
        ],
    ],
],
```
`Item` model code:

```php

use hauntd\vote\behaviors\VoteBehavior;
use yii\db\ActiveRecord;

class Item extends ActiveRecord
{
    public static function tableName()
    {
        return '{{%item}}';
    }

    public function behaviors()
    {
        return [
            VoteBehavior::class,
        ];
    }

    public static function find()
    {
        return new ItemQuery(get_called_class());
    }
}
```

`ItemQuery` code:
```php

use hauntd\vote\behaviors\VoteQueryBehavior;

class ItemQuery extends \yii\db\ActiveQuery
{
    public function behaviors()
    {
        return [
            VoteQueryBehavior::class,
        ];
    }
}
```

Sort items by "likes" (desc):

```php
$query = Item::find()
    ->withVoteAggregate('itemLike')
    ->withUserVote('itemLike')
    ->orderBy('itemLikeRating desc'); // or orderBy('itemLikePositive desc')

$dataProvider = new ActiveDataProvider([
    'query' => $query,
    'pagination' => [
        'pageSize' => 50,
    ]
]);
```

Hope this helps.

**Comment by dbd5** [comment]
Hi @hauntd ,

Thanks for the response, I believe that approach covers Sorting items by "likes" or even "Favorite".

My question goes to sorting items by "Vote" considering that the voting result is managed separately in the attributes positive and negative.

if the entity definition is as follows;

'modules' => [
    'vote' => [
        ...
        'entities' => [
                'itemVote' => common\models\Item::class,
        ],
    ],
],

Remember we want to sort items by the result of positive - negative (to get an item's true position in the list, an item can have **13 positive votes and 200 negative votes** so its position will be 13 - 200 = -187 )

Will the following query be valid?

$query = Item::find()
    ->withVoteAggregate('itemVote')
    ->withUserVote('itemVote')
    ->orderBy('itemLikePositive - itemLikeNegative desc')

**Comment by hauntd** [comment]
@dbd5, oh I see. Well, this should work:

```php
 $query = Item::find()
    ->withVoteAggregate('itemVote')
    ->withUserVote('itemVote')
    ->addSelect('(itemVoteAggregate.positive - itemVoteAggregate.negative) as rating')
    ->orderBy('rating desc');
```
(vote table alias = "{entity}Aggregate", in this example **itemVote**Aggregate

**Comment by dbd5** [comment]
Perfect, I will test and revert

Thank you

**Comment by dbd5** [comment]
It works great, thanks!
