### ISSUE TITLE
Naming of Entities - Syntax error or access violation

### ISSUE THREAD

**Issue by dbd5** [hauntd/yii2-vote#7]
Hi @hauntd ,

The following definition in Voteform suggests that dots can be used in entity names;
    /**
     * @var string entity (e.g. "user.like" or "page.voting")
     */
    public $entity;

However, this seems to cause problems when you use the aggregate functions and throws an error like this;

SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'response' 

The entities were defined as follows;

                'response.Favorite' => [
                    'modelName' => common\models\Response::class,
                    'type' => hauntd\vote\Module::TYPE_TOGGLE,
                ],
                'response.Vote' => common\models\Response::class,

Is there a way to resolve this?

**Comment by hauntd** [comment]
Hi @dbd5,

Current module realization doesn't support dots and many other special symbols for entity names  (I have fixed that comment, thanks), because this entity name is used later in the model behaviors:

```php
$item->responseFavoriteRating // ok
$item->response.FavoriteRating // error
```

You may use a-zA-Z symbols, in camelCase for example:

```php
'responseFavorite' => [
   'modelName' => common\models\Response::class,
   'type' => hauntd\vote\Module::TYPE_TOGGLE,
],
'responseVote' => [
   'modelName' => common\models\Response::class,
   'type' => hauntd\vote\Module::TYPE_TOGGLE,
],
```

**Comment by dbd5** [comment]
Thanks, noted
